= Risk Mitigation
The following chart gives a high-level overview of the risk tracking status (including mitigated risks):

[vegalite]
....
{
  "width": 400,
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {"risk": "Low (6)", "value": 0, "status": "Unchecked", "color": "#FF0000"},
      {"risk": "Low (6)", "value": 0, "status": "InDiscussion", "color": "#FF9300"},
      {"risk": "Low (6)", "value": 3, "status": "Accepted", "color": "#FF40FF"},
      {"risk": "Low (6)", "value": 1, "status": "InProgress", "color": "#0000FF"},
      {"risk": "Low (6)", "value": 0, "status": "Mitigated", "color": "#008F00"},
      {"risk": "Low (6)", "value": 2, "status": "FalsePositive", "color": "#666666"},

      {"risk": "Medium (38)", "value": 0, "status": "Unchecked", "color": "#FF0000"},
      {"risk": "Medium (38)", "value": 0, "status": "InDiscussion", "color": "#FF9300"},
      {"risk": "Medium (38)", "value": 7, "status": "Accepted", "color": "#FF40FF"},
      {"risk": "Medium (38)", "value": 17, "status": "InProgress", "color": "#0000FF"},
      {"risk": "Medium (38)", "value": 0, "status": "Mitigated", "color": "#008F00"},
      {"risk": "Medium (38)", "value": 14, "status": "FalsePositive", "color": "#666666"},

      {"risk": "Elevated (21)", "value": 0, "status": "Unchecked", "color": "#FF0000"},
      {"risk": "Elevated (21)", "value": 0, "status": "InDiscussion", "color": "#FF9300"},
      {"risk": "Elevated (21)", "value": 4, "status": "Accepted", "color": "#FF40FF"},
      {"risk": "Elevated (21)", "value": 13, "status": "InProgress", "color": "#0000FF"},
      {"risk": "Elevated (21)", "value": 0, "status": "Mitigated", "color": "#008F00"},
      {"risk": "Elevated (21)", "value": 4, "status": "FalsePositive", "color": "#666666"},

      {"risk": "High (2)", "value": 0, "status": "Unchecked", "color": "#FF0000"},
      {"risk": "High (2)", "value": 0, "status": "InDiscussion", "color": "#FF9300"},
      {"risk": "High (2)", "value": 0, "status": "Accepted", "color": "#FF40FF"},
      {"risk": "High (2)", "value": 1, "status": "InProgress", "color": "#0000FF"},
      {"risk": "High (2)", "value": 1, "status": "Mitigated", "color": "#008F00"},
      {"risk": "High (2)", "value": 0, "status": "FalsePositive", "color": "#666666"},

      {"risk": "Critical (0)", "value": 0, "status": "Unchecked", "color": "#FF0000"},
      {"risk": "Critical (0)", "value": 0, "status": "InDiscussion", "color": "#FF9300"},
      {"risk": "Critical (0)", "value": 0, "status": "Accepted", "color": "#FF40FF"},
      {"risk": "Critical (0)", "value": 0, "status": "InProgress", "color": "#0000FF"},
      {"risk": "Critical (0)", "value": 0, "status": "Mitigated", "color": "#008F00"},
      {"risk": "Critical (0)", "value": 0, "status": "FalsePositive", "color": "#666666"}
    ]
  },
  "mark": {"type": "bar", "cornerRadiusTopLeft": 3, "cornerRadiusTopRight": 3},
  "encoding": {
    "x": {"field": "risk", "type": "ordinal", "title": "", "sort": [], "axis": {
        "labelAngle": 0
    }},
    "y": {"field": "value", "type": "quantitative", "title": "", "axis": {
      "orient": "right"
    }},
    "color": {
      "field": "status",
      "scale": {
        "domain": ["Unchecked", "InDiscussion", "Accepted", "InProgress", "Mitigated", "FalsePositive"],
        "range": ["#FF0000", "#FF9300", "#FF40FF", "#0000FF", "#008F00", "#666666"]
      },
      "legend" : {
        "title": "",
        "labelExpr": "datum.label == \"Unchecked\" ? \"0 unchecked\" : datum.label == \"InDiscussion\" ? \"0 in discussion\" : datum.label == \"Accepted\" ? \"14 accepted\" : datum.label == \"InProgress\" ? \"32 in progress\" : datum.label == \"Mitigated\" ? \"1 mitigated\" : datum.label == \"FalsePositive\" ? \"20 false positive\" : \"\""
      }
    }
  }
}
....


After removal of risks with status _mitigated_ and _false positive_ the following *46 remain unmitigated*:
[cols="a,a",frame=none,grid=none]
|===
|
[mermaid]
....
%%{init: {'pie' : {'textPosition' : 0.5}, 'theme': 'base', 'themeVariables': { 'pie1': '#FF2600', 'pie2': '#A0281E', 'pie3': '#FF8E00', 'pie4': '#C87832', 'pie5': '#23465F'}}}%%
pie showData
  "unmitigated critical risk" : 0
  "unmitigated high risk" : 1
  "unmitigated elevated risk" : 17
  "unmitigated medium risk" : 24
  "unmitigated low risk" : 4
....

|
[mermaid]
....
%%{init: {'pie' : {'textPosition' : 0.5}, 'theme': 'base', 'themeVariables': { 'pie1': '#531B93', 'pie2': '#005493', 'pie3': '#DE9223', 'pie4': '#947F50'}}}%%
pie showData
  "business side related" : 1
  "architecture related" : 8
  "development related" : 3
  "operations related" : 34
....
|===

