= Impact Analysis Of 35 Remaining Risks In 18 Categories
:fn-risk-findings: footnote:riskfinding[Risk finding paragraphs are clickable and link to the corresponding chapter.]
The most prevalent impacts of the *35 remaining risks* (distributed over *18 risk categories*) are (taking the severity ratings into account and using the highest for each category)!{fn-risk-findings}

<<sql-nosql-injection,[.HighRisk]#High: *SQL/NoSQL-Injection*: 3 Remaining Risks - Exploitation likelihood is _Very Likely_ with _High_ impact.#>>::
If this risk is unmitigated, attackers might be able to modify SQL/NoSQL queries to steal and modify data and eventually further escalate towards a deeper system penetration via code executions.

<<hardcoded-credentials,[.ElevatedRisk]#Elevated: *Hardcoded Credentials in Container Configuration*: 1 Remaining Risk - Exploitation likelihood is _Likely_ with _High_ impact.#>>::
An attacker who obtains the compose file or inspects container environment variables gains immediate authenticated access to the affected datastore without further exploitation.

<<missing-authentication,[.ElevatedRisk]#Elevated: *Missing Authentication*: 1 Remaining Risk - Exploitation likelihood is _Likely_ with _High_ impact.#>>::
If this risk is unmitigated, attackers might be able to access or modify sensitive data in an unauthenticated way.

<<missing-cloud-hardening,[.ElevatedRisk]#Elevated: *Missing Cloud Hardening*: 1 Remaining Risk - Exploitation likelihood is _Unlikely_ with _Very High_ impact.#>>::
If this risk is unmitigated, attackers might access cloud components in an unintended way.

<<missing-hardening,[.ElevatedRisk]#Elevated: *Missing Hardening*: 3 Remaining Risks - Exploitation likelihood is _Likely_ with _Medium_ impact.#>>::
If this risk remains unmitigated, attackers might be able to easier attack high-value targets.

<<path-traversal,[.ElevatedRisk]#Elevated: *Path-Traversal*: 1 Remaining Risk - Exploitation likelihood is _Very Likely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to read sensitive files (configuration data, key/credential files, deployment files, business data files, etc.) from the filesystem of affected components.

<<sql-nosql-injection,[.ElevatedRisk]#Elevated: *SQL/NoSQL-Injection*: 3 Remaining Risks - Exploitation likelihood is _Very Likely_ with _High_ impact.#>>::
If this risk is unmitigated, attackers might be able to modify SQL/NoSQL queries to steal and modify data and eventually further escalate towards a deeper system penetration via code executions.

<<server-side-request-forgery,[.ElevatedRisk]#Elevated: *Server-Side Request Forgery (SSRF)*: 2 Remaining Risks - Exploitation likelihood is _Likely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to access sensitive services or files of network-reachable components by modifying outgoing calls of affected components.

<<unencrypted-communication,[.ElevatedRisk]#Elevated: *Unencrypted Communication*: 4 Remaining Risks - Exploitation likelihood is _Likely_ with _High_ impact.#>>::
If this risk is unmitigated, network attackers might be able to to eavesdrop on unencrypted sensitive data sent between components.

<<unguarded-direct-datastore-access,[.ElevatedRisk]#Elevated: *Unguarded Direct Datastore Access*: 3 Remaining Risks - Exploitation likelihood is _Likely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to directly attack sensitive data stores without any protecting components in-between.

<<container-baseimage-backdooring,[.MediumRisk]#Medium: *Container Base Image Backdooring*: 5 Remaining Risks - Exploitation likelihood is _Unlikely_ with _High_ impact.#>>::
If this risk is unmitigated, attackers might be able to deeply persist in the target system by executing code in deployed containers.

<<missing-build-infrastructure,[.MediumRisk]#Medium: *Missing Build Infrastructure*: 1 Remaining Risk - Exploitation likelihood is _Unlikely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to exploit risks unseen in this threat model due to critical build infrastructure components missing in the model.

<<missing-hardening,[.MediumRisk]#Medium: *Missing Hardening*: 3 Remaining Risks - Exploitation likelihood is _Likely_ with _Medium_ impact.#>>::
If this risk remains unmitigated, attackers might be able to easier attack high-value targets.

<<missing-identity-store,[.MediumRisk]#Medium: *Missing Identity Store*: 1 Remaining Risk - Exploitation likelihood is _Unlikely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to exploit risks unseen in this threat model in the identity provider/store that is currently missing in the model.

<<missing-authentication-second-factor,[.MediumRisk]#Medium: *Missing Two-Factor Authentication (2FA)*: 1 Remaining Risk - Exploitation likelihood is _Unlikely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to access or modify highly sensitive data without strong authentication.

<<missing-vault,[.MediumRisk]#Medium: *Missing Vault (Secret Storage)*: 1 Remaining Risk - Exploitation likelihood is _Unlikely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to easier steal config secrets (like credentials, private keys, client certificates, etc.) once a vulnerability to access files is present and exploited.

<<missing-waf,[.MediumRisk]#Medium: *Missing Web Application Firewall (WAF)*: 1 Remaining Risk - Exploitation likelihood is _Unlikely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to apply standard attack pattern tests at great speed without any filtering.

<<mixed-targets-on-shared-runtime,[.MediumRisk]#Medium: *Mixed Targets on Shared Runtime*: 1 Remaining Risk - Exploitation likelihood is _Unlikely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers successfully attacking other components of the system might have an easy path towards more valuable targets, as they are running on the same shared runtime.

<<unencrypted-asset,[.MediumRisk]#Medium: *Unencrypted Technical Assets*: 2 Remaining Risks - Exploitation likelihood is _Unlikely_ with _High_ impact.#>>::
If this risk is unmitigated, attackers might be able to access unencrypted data when successfully compromising sensitive components.

<<unguarded-direct-datastore-access,[.MediumRisk]#Medium: *Unguarded Direct Datastore Access*: 3 Remaining Risks - Exploitation likelihood is _Likely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to directly attack sensitive data stores without any protecting components in-between.

<<dos-risky-access-across-trust-boundary,[.LowRisk]#Low: *DoS-risky Access Across Trust-Boundary*: 3 Remaining Risks - Exploitation likelihood is _Unlikely_ with _Low_ impact.#>>::
If this risk remains unmitigated, attackers might be able to disturb the availability of important parts of the system.

