#!/usr/bin/env python3
"""
scripts/create-tickets.py
Creates GitHub Issues for new high-severity risks found by the threat model diff.
"""
import json
import argparse
import urllib.request


def create_issue(repo, token, title, body, labels):
    """Create a GitHub issue via REST API."""
    url = f"https://api.github.com/repos/{repo}/issues"
    data = json.dumps({'title': title, 'body': body, 'labels': labels}).encode()

    req = urllib.request.Request(url, data=data, method='POST')
    req.add_header('Authorization', f'token {token}')
    req.add_header('Content-Type', 'application/json')
    req.add_header('Accept', 'application/vnd.github.v3+json')

    with urllib.request.urlopen(req) as resp:
        result = json.loads(resp.read())
        print(f"Created issue #{result['number']}: {result['title']}")
        return result['number']


def main():
    parser = argparse.ArgumentParser(description='Create GitHub Issues for threat model findings')
    parser.add_argument('--diff',         required=True, help='Path to diff-report.json')
    parser.add_argument('--min-severity', default='elevated', help='Minimum severity to create ticket for')
    parser.add_argument('--repo',         required=True, help='GitHub repo in owner/name format')
    parser.add_argument('--token',        required=True, help='GitHub personal access token')
    args = parser.parse_args()

    severity_order = ['low', 'medium', 'elevated', 'critical']
    try:
        min_idx = severity_order.index(args.min_severity)
    except ValueError:
        print(f"Unknown severity: {args.min_severity}. Using 'elevated'.")
        min_idx = severity_order.index('elevated')

    with open(args.diff) as f:
        diff = json.load(f)

    created = 0
    for risk in diff.get('new_risks', []):
        sev = risk.get('severity', 'medium')
        try:
            sev_idx = severity_order.index(sev)
        except ValueError:
            sev_idx = 0

        if sev_idx >= min_idx:
            risk_id = risk.get('synthetic_id', risk.get('id', 'unknown'))
            title = f"[Threat Model] {risk.get('title', risk_id)}"
            body = (
                f"**Severity**: {sev}\n"
                f"**Category**: {risk.get('category', 'N/A')}\n"
                f"**Synthetic ID**: `{risk_id}`\n"
                f"**Affected Asset**: {risk.get('most_relevant_technical_asset', 'N/A')}\n\n"
                f"**Description**:\n{risk.get('description', 'See Threagile report for details.')}\n\n"
                f"**Suggested Mitigation**:\n{risk.get('mitigation', 'Review and mitigate per security policy.')}\n\n"
                f"---\n"
                f"*Auto-generated by the VaultNote threat modeling pipeline.*\n"
                f"*Add a `risk_tracking` entry to `threagile/threagile.yaml` to acknowledge this risk.*"
            )
            create_issue(
                args.repo, args.token, title, body,
                labels=['security', 'threat-model', sev]
            )
            created += 1

    print(f"\nCreated {created} issue(s) for risks at or above '{args.min_severity}' severity.")


if __name__ == '__main__':
    main()
